ViewModels/BasketViewModel.cs
using Aurora.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aurora.ViewModels
{
    public class BasketViewModel
    {
        public Basket Basket { get; set; }
        public decimal BasketTotal { get; set; }
    }
}

Controllers/BasketController.cs
using Aurora.Data.Interfaces;
using Aurora.Data.Models;
using Aurora.TagHelpers;
using Aurora.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Aurora.Controllers
{
    public class BasketController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly Basket _basket;
        private readonly IHttpContextAccessor _httpContextAccessor; 
    
        public BasketController(IProductRepository productRepository, Basket basket)
        {
            _productRepository = productRepository;
            _basket = basket;
        }

        public ViewResult Index()
        {
        
            var items = _basket.GetCartItems();
            _basket.BasketItems = items;

            var basketViewModel = new BasketViewModel
            {
                Basket = _basket,
                BasketTotal = _basket.GetCartTotal()
            };
            return View(basketViewModel);
        }


        public RedirectToActionResult AddToBasket(int productId)
        {
            var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (selectedProduct != null)
            {
                _basket.AddToCart(selectedProduct, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromBasket(int productId)
        {
            var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (selectedProduct != null)
            {
                _basket.RemoveFromCart(selectedProduct);
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/OrderController.cs
using Aurora.Data.Interfaces;
using Aurora.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aurora.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly Basket _basket;

        public OrderController(IOrderRepository orderRepository, Basket basket)
        {
            _orderRepository = orderRepository;
            _basket = basket;
        }

        
        public IActionResult Checkout()
        {
            return View();
        } 

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _basket.GetCartItems();
            _basket.BasketItems = items;
            if (_basket.BasketItems.Count == 0)
            {
                ModelState.AddModelError("", "Your basket is empty, add some products first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _basket.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! :) ";
            return View();
        }
    }
}

Views/Basket/Index.cshtml
@model Aurora.ViewModels.BasketViewModel

<div class="row checkoutForm">
    <h2>Ваша корзина</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Количество</th>
                <th>Продукт</th>
                <th class="text-right">Цена</th>
                <th class="text-right">Итого</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Basket.BasketItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Product.Name</td>
                    <td class="text-right">@line.Product.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Product.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="Basket" asp-action="RemoveFromBasket" asp-route-productId="@line.Product.ProductId">удалить</a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Итого:</td>
                <td class="text-right">
                    @Model.BasketTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-dark" asp-controller="Order" asp-action="Checkout">Заказать</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Добавить больше продуктов<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Product" asp-action="List" asp-route-category="Rings">Кольца</a></li>
                    <li><a asp-controller="Product" asp-action="List" asp-route-category="Braslets">Браслеты</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>